name: CI/CD + Server Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¦ Kodni yuklab olish
        uses: actions/checkout@v3

      - name: ðŸ§° Node.js oâ€˜rnatish
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ðŸ“¥ Dependency oâ€˜rnatish
        run: npm ci

      - name: ðŸ—ï¸ Build yaratish
        run: npm run build

      # --- GitHub Pages Deploy ---
      - name: ðŸš€ Deploy GitHub Pagesâ€™ga
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist

      # 5ï¸âƒ£ Serverga upload qilish (scp orqali)
      - name: Deploy to Ubuntu Server
        uses: appleboy/scp-action@v0.1.4
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
          SSH_TARGET: ${{ secrets.SSH_TARGET }}
        run: |
          echo "$SSH_SECRET_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -P $SSH_PORT -i private_key.pem -r dist/* $SSH_USERNAME@$SSH_HOST:$SSH_TARGET
